platform:ios,'7.0'
target 'PersonalImprovement' do
pod 'EAIntroView'
#pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'CYLTabBarController'
pod 'HPGrowingTextView'
pod 'WYPopoverController'
pod 'MJRefresh'
pod 'PSTCollectionView'
pod 'MagicalRecord'
pod 'SSKeychain'
pod 'AFSoundManager'
pod 'CocoaAsyncSocket'
pod 'DateTools'
pod 'EAIntroView'
pod 'SMPageControl', '~> 1.2'
pod 'FoldingTabBar'
pod 'JKCategories'
pod 'JazzHands'
pod 'JDStatusBarNotification'
pod 'InfColorPicker'
pod 'FTFontSelector'
pod 'KYCuteView'
pod 'KYGooeyMenu'
pod 'INTULocationManager'
pod 'M13ProgressSuite'
pod 'MarqueeLabel'
pod 'MMDrawerController'
pod 'MRProgress'
pod 'MTAnimation'
pod 'SVProgressHUD'
pod 'Onboard'
pod 'pop'
pod 'PQFCustomLoaders'
pod 'RBBAnimation'
pod 'REMenu'
pod 'Shapes'
pod 'SWTableViewCell'
pod 'TapkuLibrary'
pod 'TGCameraViewController'
pod 'TSMessages'
pod 'WYPopoverController'
pod 'XLForm'
pod 'AXRatingView', '1.0.3'
pod 'JVFloatLabeledTextField', '1.0.2'
pod 'YLProgressBar'
pod 'ReactiveCocoa'
pod 'libextobjc'
pod 'ReactiveViewModel', '0.1.1'
pod 'LinqToObjectiveC'
pod 'objectiveflickr'
pod 'YYKit'
pod 'ChatKit', '~> 0.7.2'
pod 'MLPAutoCompleteTextField'
pod 'TWMessageBarManager'
pod 'FTPopOverMenu'
pod 'BabyBluetooth'

pod 'SCLAlertView-Objective-C', '~> 0.7.3'
pod 'TTTAttributedLabel'
pod 'SVWebViewController'
pod 'XHImageViewer'
pod 'DACircularProgress'
pod 'ZXingObjC'


#pod 'JSQMessagesViewController'

pod 'DOUAudioStreamer', '0.2.11'
pod 'GVUserDefaults'
pod 'Mantle', '1.5.5'

end
